export const groupNamesBanglaMap: Record<string, string> = {
  All: "All Channels",
  Bangla: "Bangla",
  "Indian Bangla": "Indian Bangla",
  News: "News",
  Sports: "Sports",
  Kids: "Kids",
  Movies: "Movies",
  Movie: "Movie",
  Music: "Music",
  Religious: "Religious",
  Islamic: "Islamic",
  Weather: "Weather",
  Documentary: "Documentary",
  "Documentaries (EN)": "Documentaries",
  English: "English",
  Hindi: "Hindi",
  Channels: "Channels",
  General: "General",
  Entertainment: "Entertainment",
  Education: "Education",
  Educational: "Educational",
  Culture: "Culture",
  Lifestyle: "Lifestyle",
  Business: "Business",
  Series: "Series",
  "Web Series": "Web Series",
  Legislative: "Legislative",
  Shop: "Shop",
  Other: "Other",
  Others: "Others",
  Bangladesh: "বাংলাদেশ",
  Undefined: "Uncategorized",
  Imported: "Imported"
};
