export const groupNamesBanglaMap: Record<string, string> = {
  All: "All Channels",
  Bangladesh: "Bangladesh / Bangla",
  Bangla: "Bangla",
  "Indian Bangla": "Indian Bangla",
  India: "India / Hindi",
  News: "News",
  Sports: "Sports",
  Kids: "Kids",
  Movies: "Movies",
  Movie: "Movie",
  Series: "Series",
  "Web Series": "Web Series",
  Music: "Music",
  Religious: "Religious",
  Islamic: "Islamic",
  Weather: "Weather",
  Documentary: "Documentary",
  "Documentaries (EN)": "Documentaries",
  English: "English",
  Hindi: "Hindi",
  Channels: "Channels",
  General: "General",
  Entertainment: "Entertainment",
  Education: "Education",
  Educational: "Educational",
  Culture: "Culture",
  Lifestyle: "Lifestyle",
  Travel: "Travel / Outdoor",
  Comedy: "Comedy / Classic",
  Business: "Business",
  Government: "Public / Govt",
  Legislative: "Public / Govt",
  Shopping: "Shopping",
  Shop: "Shopping",
  International: "International",
  Other: "Other",
  Others: "Others",
  Undefined: "Uncategorized",
  Imported: "Imported",
};
